In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder # 전처리

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

np.random.seed(3)
tf.random.set_seed(3)
df = pd.read_csv('../data/iris.csv',
                names=['sepal_length', 'sepal_width', 'petal_lengh', 'petal_width',
                      'species'])

# 그래프로 확인
sns.pairplot(df, hue='species')
plt.show()

C:\Users\has91\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


<Figure size 1143.38x1000 with 20 Axes>

In [2]:
# 데이터 분류
dataset = df.values
X = dataset[:, 0:4].astype(float) #숫자
Y_obj = dataset[:,4] # 문자열

# LabelENcoder를 이용해 문자열을 숫자로 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)
print(Y)

Y_encoded = tf.keras.utils.to_categorical(Y) # 활성화 함수 적용
print(Y_encoded)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.

In [5]:
# 모델의 설정
model = Sequential()
model.add(Dense(16, input_dim=4, activation='relu')) # input 4
model.add(Dense(3, activation='softmax')) #출력값 3, softmax

# 모델 컴파일
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

# 모델 실행
model.fit(X, Y_encoded, epochs=50, batch_size=1)

# 결과 출력
print('\n Accuracy: %.4f' %(model.evaluate(X, Y_encoded)[1]))


Epoch 1/50
150/150 [==============================] - 0s 606us/step - loss: 1.4214 - accuracy: 0.3200
Epoch 2/50
150/150 [==============================] - 0s 547us/step - loss: 0.8921 - accuracy: 0.5467
Epoch 3/50
150/150 [==============================] - 0s 574us/step - loss: 0.7284 - accuracy: 0.7000
Epoch 4/50
150/150 [==============================] - 0s 586us/step - loss: 0.6266 - accuracy: 0.6933
Epoch 5/50
150/150 [==============================] - 0s 665us/step - loss: 0.5578 - accuracy: 0.7067
Epoch 6/50
150/150 [==============================] - 0s 619us/step - loss: 0.5026 - accuracy: 0.8333
Epoch 7/50
150/150 [==============================] - 0s 592us/step - loss: 0.4616 - accuracy: 0.8800
Epoch 8/50
150/150 [==============================] - 0s 625us/step - loss: 0.4358 - accuracy: 0.8933
Epoch 9/50
150/150 [==============================] - 0s 623us/step - loss: 0.4078 - accuracy: 0.9267
Epoch 10/50
150/150 [==============================] - 0s 617us/step - loss: 0.384

In [3]:
a = tf.keras.utils.to_categorical([0, 1, 2, 3], num_classes=4)
a = tf.constant(a, shape=[4, 4])
print(a)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
