In [1]:
import numpy as np
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding


## 토큰화

In [4]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text = "해보지 않으면 해낼 수 없다"
result = text_to_word_sequence(text) # text_to_word_sequence() : 토큰화
print('\n원문:\n', text)
print('\n토큰화:\n', result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


# 빈도수

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 테스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

token = Tokenizer() #토큰화 함수 지정
token.fit_on_texts(docs) #토큰화 함수에 문장 적용

print("\n단어 카운트:\n", token.word_counts) #단어의 빈도 수를 계산한 결과 출력

print("\n문장 카운트: ", token.document_count)

# word_docs() : 각 단어가 몇개의 문장에서 나오는 지 출력
print("\n각 단어가 몇개의 문장에 포함되어 있는가:\n", token.word_docs) 

# word_index() : 각 단어에 매겨진 인덱스 값을 출력
print("\n각 단어에 매겨진 인덱스 값:\n", token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('테스트의', 1), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('텍스트의', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'먼저': 1, '토큰화합니다': 1, '각': 1, '테스트의': 1, '나누어': 1, '단어를': 1, '인식됩니다': 1, '텍스트의': 1, '딥러닝에서': 2, '단어로': 1, '토큰화해야': 1, '토큰화한': 1, '수': 1, '사용할': 1, '있습니다': 1, '결과는': 1})

각 단어에 매겨진 인덱스 값:
 {'딥러닝에서': 1, '먼저': 2, '테스트의': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '텍스트의': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


## 단어의 원-핫 인코딩

In [13]:
from tensorflow.keras.preprocessing.text import Tokenizer

text = '오랫동안 꿈꾸는 이는 그 꿈을 닮아간다'

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index) # 단어 단위로 토큰화하고 단어의 인덱스 값 출력

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [15]:
x = token.texts_to_sequences([text])
print(x) # 인덱스로만 채워진 배열

[[1, 2, 3, 4, 5, 6]]


In [18]:
# to_categorical() 함수를 사용해
# 1~6까지의 정수로 이루어진 배열을 0과 1로만 이루어진 배열로 변경

from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index)+1
x = to_categorical(x, num_classes=word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 단어 임베딩

In [21]:
# 단어의 유사도 계산
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(16, 4)) # 입력될 총 단어 수는 16, 임베딩 후 출력 되는 벡터 크기는 4

# 텍스트를 읽고 긍정, 부정 예측하기

In [27]:
# 짧은 리뷰 10개를 불러와 긍정이면 1, 부정이면 0 클래스로 지정

# 텍스트 리뷰를 지정
docs = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다',
       '한 번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요',
       '연기가 어색해요', '재미없어요']

# 긍정리뷰는 1, 부정리뷰는 0으로 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [32]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n 리뷰 텍스트, 토큰화 결과:\n", x)
padded_x = pad_sequences(x, 4) # 길이를 4로 맞춤
print('\n 패딩 결과:\n', padded_x)
print('\n 딥러닝 모델 시작:')
word_size = len(token.word_index) + 1 # 맨앞엔 0이 나와야하기 때문에 +1
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4)) # 입력, 출력, 단어 수
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy',
            metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print('\n Accuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}

 리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]

 패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]

 딥러닝 모델 시작:
Epoch 1/20
1/1 [==============================] - 0s 2ms/step - loss: 0.6970 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6951 - accuracy: 0.6000
Epoch 3/20
1/1 [==============================] - 0s 1ms/step - loss: 0.6933 - accuracy: 0.6000
Epoch 4/20
1/1 [==============================] - 0s 0s/step - loss: 0.6914 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 1000us/step - loss: 0.6896 - accuracy: 0.6000
Epoc